-- MySQL Script generated by MySQL Workbench
-- Sun Aug 23 23:27:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retrowavedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `retrowavedb` ;

-- -----------------------------------------------------
-- Schema retrowavedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retrowavedb` DEFAULT CHARACTER SET utf8 ;
USE `retrowavedb` ;

-- -----------------------------------------------------
-- Table `retrowavedb`.`Gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrowavedb`.`Gerente` ;

CREATE TABLE IF NOT EXISTS `retrowavedb`.`Gerente` (
  `idGerente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idGerente`),
  UNIQUE INDEX `idGerente_UNIQUE` (`idGerente` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retrowavedb`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrowavedb`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `retrowavedb`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `Gerente_idGerente` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`, `Gerente_idGerente`),
  UNIQUE INDEX `idFuncionario_UNIQUE` (`idFuncionario` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_Funcionario_Gerente1_idx` (`Gerente_idGerente` ASC),
  CONSTRAINT `fk_Funcionario_Gerente1`
    FOREIGN KEY (`Gerente_idGerente`)
    REFERENCES `retrowavedb`.`Gerente` (`idGerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retrowavedb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrowavedb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `retrowavedb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retrowavedb`.`Itens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrowavedb`.`Itens` ;

CREATE TABLE IF NOT EXISTS `retrowavedb`.`Itens` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `periodoLoc` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `quant` INT NOT NULL,
  PRIMARY KEY (`idItem`),
  UNIQUE INDEX `idItem_UNIQUE` (`idItem` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retrowavedb`.`Locacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retrowavedb`.`Locacao` ;

CREATE TABLE IF NOT EXISTS `retrowavedb`.`Locacao` (
  `idLoc` INT NOT NULL AUTO_INCREMENT,
  `Itens_idItem` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  `dataInicial` DATE NOT NULL,
  `dataFinal` DATE NOT NULL,
  `valorTotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idLoc`, `Itens_idItem`, `Cliente_idCliente`, `Funcionario_idFuncionario`),
  INDEX `fk_Locacao_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Locacao_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Locacao_Itens1`
    FOREIGN KEY (`Itens_idItem`)
    REFERENCES `retrowavedb`.`Itens` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `retrowavedb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `retrowavedb`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- ----------------
-- Insert Inicial --
-- ---------------

-- -----------------------------------------------------
-- Table `retrowavedb`.`Gerente`
-- -----------------------------------------------------

INSERT INTO `gerente` (`idGerente`,`nome`,`cpf`,`salario`,`telefone`,`senha`,`endereco`,`email`)  VALUES (1,'Thiago','33333333333',5000.00,'35933333333','admin123','Lavras','Thiago@ufla.br'); 

-- -----------------------------------------------------
-- Table `retrowavedb`.`Funcionario`
-- -----------------------------------------------------

INSERT INTO `funcionario` (`idFuncionario`,`nome`,`cpf`,`salario`,`email`,`telefone`,`senha`,`endereco`,`Gerente_idGerente`)  VALUES (1,'Matheus','55555555555',500.00,'matheus@ufla.br','35955555555','func123','Lavras','1'); 
INSERT INTO `funcionario` (`idFuncionario`,`nome`,`cpf`,`salario`,`email`,`telefone`,`senha`,`endereco`,`Gerente_idGerente`)  VALUES (2,'Lucas','44444444444',500.00,'lucas@ufla.br','35944444444','func234','Lavras','1'); 

-- -----------------------------------------------------
-- Table `retrowavedb`.`Cliente`
-- -----------------------------------------------------

INSERT INTO `cliente` (`idCliente`,`nome`,`cpf`,`email`,`telefone`,`senha`,`endereco`)  VALUES (1,'Davi','11111111111','davi@ufla.br','11911111111','123','Lavras'); 
INSERT INTO `cliente` (`idCliente`,`nome`,`cpf`,`email`,`telefone`,`senha`,`endereco`)  VALUES (2,'Ciro','22222222222','ciro@ufla.br','11922222222','234','São Paulo'); 

-- -----------------------------------------------------
-- Table `retrowavedb`.`Itens`
-- -----------------------------------------------------

INSERT INTO `itens` (`nome`,`periodoLoc`,`valor`,`quant`,`idItem`)  VALUES ('PS4',7,100.00,5,1); 
INSERT INTO `itens` (`nome`,`periodoLoc`,`valor`,`quant`,`idItem`)  VALUES ('Mario Kart',30,20.00,35,2);

-- -----------------------------------------------------
-- Table `retrowavedb`.`Locacao`
-- -----------------------------------------------------

INSERT INTO `locacao` (`dataInicial`,`dataFinal`,`valorTotal`,`Itens_idItem`,`Cliente_idCliente`,`Funcionario_idFuncionario`,`idLoc`)  VALUES ('2020/08/23','2020/08/30',100.00,1,1,1,1);
INSERT INTO `locacao` (`dataInicial`,`dataFinal`,`valorTotal`,`Itens_idItem`,`Cliente_idCliente`,`Funcionario_idFuncionario`,`idLoc`)  VALUES ('2020/08/23','2020/09/06',20.00,2,1,1,2);


